version: '1.1'

x-labels-backups-env: &default-backups-env
  RCON_PASSWORD: ${RCON_PASSWORD}
  BACKUP_METHOD: restic
  INITIAL_DELAY: 10
  PRUNE_RESTIC_RETENTION: ${PRUNE_RESTIC_RETENTION}

# x-labels-daily-restarts: &daily-restarts
#   ofelia.enabled: "true"
#   ofelia.job-exec.restart.schedule: "0 1 * * *"
#   ofelia.job-exec.restart.command: 'rcon-cli say "Restarting in 60 seconds!"; sleep 50; rcon-cli "say Restarting in 10 seconds!"; sleep 10; rcon-cli restart'

x-service-velocity-defaults: &velocity-network
  networks:
    - minecraft
    - keine_monitor
    - compose_traefik
  restart: unless-stopped
  tty: true
  stdin_open: true
  secrets:
    - velocity_forwarding_secret

x-environment-minecraft-defaults: &minecraft-env-defaults
  EULA: "TRUE"
  TYPE: "CUSTOM"
  CUSTOM_SERVER: "https://github.com/vectrix-space/ignite/releases/latest/download/ignite.jar"
  USE_IGNITE_LOADER: "true"
  # TYPE: "PURPUR"
  EXEC_DIRECTLY: "TRUE"
  # USE_AIKAR_FLAGS: "TRUE"
  JVM_OPTS: ${JVM_OPTS}
  ONLINE_MODE: "FALSE"
  ENFORCE_SECURE_PROFILE: "FALSE"
  RCON_PASSWORD: ${RCON_PASSWORD}
  REPOSILITE_PLUGINS_TOKEN: ${REPOSILITE_PLUGINS_TOKEN}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

services:

  velocity:
    <<: *velocity-network
    image: ghcr.io/gensokyo-reimagined/proxy:master
    ports:
      - "25565:25577"
    volumes:
      - "${DIR_MINECRAFT}/velocity:/server"
      - "${DIR_CONFIGS}/velocity:/server-config"
    environment:
      SERVER_NAME: "velocity"
      TYPE: VELOCITY
      VELOCITY_VERSION: "3.3.0-SNAPSHOT"
      VELOCITY_BUILD_ID: "343"
      MEMORY: "4096m"
      ANSIBLE_PULL_BRANCH: main
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    sysctls:
      - net.ipv4.tcp_congestion_control=bbr

  minecraft-build:
    image: ghcr.io/gensokyo-reimagined/ignite:master
    <<: *velocity-network
    environment:
      <<: *minecraft-env-defaults
      SERVER_NAME: "build"
      VERSION: "1.20.4"
      MEMORY: "32G"
      ANSIBLE_PULL_BRANCH: main
      EXTRA_ARGS: '--world-container ./worlds/'
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - "${DIR_MINECRAFT}/build:/data"
      - "${DIR_CONFIGS}/build:/server-config"
      - "${DIR_DOCKER_DATA}/bbmodels/blueprints:/plugins/ModelEngine/blueprints"
    build:
      context: .
      secrets:
        - velocity_forwarding_secret
    labels:
      traefik.enable: 'true'
      traefik.docker.network: compose_traefik
      
      traefik.http.routers.minecraft-build.rule: Host(`build.pack.gensokyoreimagined.net`)
      traefik.http.routers.minecraft-build.entrypoints: websecure
      traefik.http.routers.minecraft-build.tls.certresolver: letsencrypt
      traefik.http.routers.minecraft-build.service: minecraft-build
      traefik.http.services.minecraft-build.loadbalancer.server.port: 8082

      traefik.http.routers.minecraft-build-map.rule: Host(`map.gensokyoreimagined.net`)
      traefik.http.routers.minecraft-build-map.entrypoints: websecure
      traefik.http.routers.minecraft-build-map.tls.certresolver: letsencrypt
      traefik.http.routers.minecraft-build-map.service: minecraft-build-map-service
      traefik.http.services.minecraft-build-map-service.loadbalancer.server.port: 8080
    sysctls:
      - net.ipv4.tcp_congestion_control=bbr
      
    # labels:
      # <<: [*daily-restarts]

  # minecraft-mmo:
  #   image: ghcr.io/gensokyo-reimagined/minecraft:master
  #   <<: *velocity-network
  #   environment:
  #     <<: *minecraft-env-defaults
  #     SERVER_NAME: "mmo"
  #     VERSION: "1.20.4"
  #     MEMORY: "16G"
  #     ANSIBLE_PULL_BRANCH: main
  #     EXTRA_ARGS: '--world-container ./worlds/'
  #     GITHUB_TOKEN: ${GITHUB_TOKEN}
  #   volumes:
  #     - "${DIR_MINECRAFT}/mmo:/data"
  #     - "${DIR_CONFIGS}/mmo:/server-config"
  #     - "${DIR_DOCKER_DATA}/bbmodels/blueprints:/plugins/ModelEngine/blueprints"
  #   labels:
  #     <<: [*daily-restarts]

#   minecraft-survival:
#     image: ghcr.io/gensokyo-reimagined/minecraft:master
#     <<: *velocity-network
#     environment:
#       <<: *minecraft-env-defaults
#       SERVER_NAME: "survival"
#       VERSION: "1.20.4"
#       PAPERBUILD: "172"
#       MEMORY: "8G"
#       KEEPUP: "false"
#       ANSIBLE_PULL_BRANCH: master
#       EXTRA_ARGS: '--world-container ./worlds/'
#     volumes:
#       - "${DIR_MINECRAFT}/survival:/data"
#       - "${DIR_CONFIGS}/survival:/server-config"
#       - "${DIR_DOCKER_DATA}/bbmodels/blueprints:/plugins/ModelEngine/blueprints"
#     labels:
#       <<: [*daily-restarts]

#   minecraft-archive:
#     image: ghcr.io/gensokyo-reimagined/minecraft:master
#     cpus: '4.0'
#     <<: *velocity-network
#     environment:
#       <<: *minecraft-env-defaults
#       SERVER_NAME: "archive"
#       EXEC_DIRECTLY: "false"
#       VERSION: "1.20.4"
#       MEMORY: "3G"
#       ENABLE_AUTOPAUSE: "TRUE"
#       OVERRIDE_SERVER_PROPERTIES: "TRUE"
#       MAX_TICK_TIME: "-1"
#       ANSIBLE_PULL_BRANCH: develop
#       UPDATE_DATA_OWNER: "true"
#       JVM_DD_OPTS: "disable.watchdog:true"
#       EXTRA_ARGS: '--world-container ./worlds/'
#     volumes:
#       - "${DIR_MINECRAFT}/archive:/data"
#       - "archive-worlds-overlay:/data/worlds"
#       - "${DIR_CONFIGS}/archive:/server-config"

  backup-build:
    image: itzg/mc-backup
    networks:
      - minecraft
      - keine_monitor
    environment:
      <<: *default-backups-env
      RCON_HOST: minecraft-build
      RESTIC_PASSWORD: ${RESTIC_PASSWORD_BUILD}
      RESTIC_REPOSITORY: rclone:backups:backups
      BACKUP_NAME: build-worlds
    volumes:
      - ${BACKUPS_RCLONE_CONF}:/config/rclone/rclone.conf:ro
      - ${DIR_MINECRAFT}/build/worlds/world:/data/world:ro

#   backup-survival:
#     image: itzg/mc-backup
#     networks:
#       - minecraft
#     environment:
#       <<: *default-backups-env
#       RCON_HOST: minecraft-survival
#       RESTIC_PASSWORD: ${RESTIC_PASWORD_SURVIVAL}
#       RESTIC_REPOSITORY: rclone:backup:survival
#       BACKUP_NAME: survival-worlds
#     volumes:
#       - ${BACKUPS_RCLONE_CONF}:/config/rclone/rclone.conf:ro
#       - ${DIR_MINECRAFT}/survival/worlds/world:/data/world:ro

  mysql:
    image: mysql
    networks:
      - minecraft
    volumes:
      - mysql:/var/lib/mysql
      - /opt/docker/compose/config/schema-migrations/:/docker-entrypoint-initdb.d:ro
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: minecraft
    restart: unless-stopped


volumes:
  filebrowser:
  mysql:
    # Non-persisting volume for archive worlds (we can delete the overlay any time to revert to the original files)
#   archive-worlds-overlay:
#     driver: local
#     driver_opts:
#       type: overlay
#       o: lowerdir=${DIR_MINECRAFT}/archive-worlds/readonly,upperdir=${DIR_MINECRAFT}/archive-worlds/upper,workdir=${DIR_MINECRAFT}/archive-worlds/work
#       device: overlay


networks:
  minecraft:
    external: true
  compose_traefik:
    external: true
  keine_monitor:
    external: true

secrets:
  velocity_forwarding_secret:
    file: "/opt/docker/data/minecraft/velocity_forwarding_secret"